<a href="https://colab.research.google.com/github/evaristo2020/Python-Clases-UTEC-2025/blob/main/C%C3%B3digo_Soluci%C3%B3n_Final_16_09_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
# Leyendo la data
data = pd.read_excel('/content/drive/MyDrive/2025 - UTEC - Grupo 6 - Proyecto Final/4. Desarrollo SolucioÃÅn - Segundo Entregable/Data/CUADRO DE CATALOGO.xlsx', header=0)

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
# Mostrando los 8 primeros registros
data.head(8)

,LEVANTAMIENTO DE INFORMACION,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
1,N¬∞ ITEM,ITEM,DESCRIPCION,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,...,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO
2,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
3,002,NaN,"3"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
4,003,NaN,"4"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
5,004,NaN,"5"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
6,005,NaN,"6"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
7,006,NaN,"8"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN

In [ ]:
data.head()

,LEVANTAMIENTO DE INFORMACION,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32
0,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
1,N¬∞ ITEM,ITEM,DESCRIPCION,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,...,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO
2,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
3,002,NaN,"3"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
4,003,NaN,"4"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN

In [ ]:
# Obteniendo el tama√±o de la data
data.shape

(765, 33)

In [ ]:
# Obteniendo el nombre de las columnas
data.columns

Index(['LEVANTAMIENTO DE INFORMACION', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32'],
      dtype='object')

In [ ]:
# Hacer que la primera fila sea la cabecera
#data.iloc[0:5, 0:3]
cabecera = data.iloc[0]

data.columns = cabecera

data.columns

Index([                                 nan,
                                        nan,
                                        nan,
                            'MEDICAL B & T',
                                        nan,
                               'MONT GROUP',
                                        nan,
                        'ALFY MEDICA S.A.C',
                                        nan,
                              'BEE MEDICAL',
                                        nan,
                                'ALKOFARMA',
                                        nan,
                                   'VALCAM',
                                        nan,
                            'FAMILY DOCTOR',
                                        nan,
                                'GE PHARMA',
                                        nan,
                                     'IRSA',
                                        nan,
                                   'KANGJI',
                                        nan,
                                     'LAPE',
                                        nan,
                                 'GEOMEDIC',
                                        nan,
                                 'IQ MEDIC',
                                        nan,
       'DROGUERIA IMP. DE ART MEDICOS S.A.',
                                        nan,
                                    'SOMOS',
                                        nan],
      dtype='object', name=0)

In [ ]:
data.head(2)

,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
0,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
1,N¬∞ ITEM,ITEM,DESCRIPCION,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,...,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO

In [ ]:
# Eliminando la primera fila
data = data[1:]
data

,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
1,N¬∞ ITEM,ITEM,DESCRIPCION,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,...,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO
2,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
3,002,NaN,"3"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
4,003,NaN,"4"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
5,004,NaN,"5"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
760,NaN,NaN,BILIRRUBINA TOTAL Y DIRECTA MONTEST (R1:200ML),False,NaN,True,NaN,False,NaN,False,...,False,NaN,False,NaN,False,NaN,False,NaN,False,NaN
761,NaN,NaN,COLESTEROL MONTEST (R1:100ML) (R1:400ML),False,NaN,True,NaN,False,NaN,False,...,False,NaN,False,NaN,False,NaN,False,NaN,False,NaN
762,NaN,NaN,HDL COLESTEROL MONTEST PRECIPITANTE (R1:200ML),False,NaN,True,NaN,False,NaN,False,...,False,NaN,False,NaN,False,NaN,False,NaN,False,NaN
763,NaN,NaN,LDL COLESTEROL MONTEST PRECIPITANTE (R1:200ML),False,NaN,True,NaN,False,NaN,False,...,False,NaN,False,NaN,False,NaN,False,NaN,False,NaN
764,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Reseteando el index
data = data.reset_index(drop = True)

data.head(2)

,NaN,NaN,NaN,MEDICAL B & T,NaN,MONT GROUP,NaN,ALFY MEDICA S.A.C,NaN,BEE MEDICAL,...,LAPE,NaN,GEOMEDIC,NaN,IQ MEDIC,NaN,DROGUERIA IMP. DE ART MEDICOS S.A.,NaN,SOMOS,NaN
0,N¬∞ ITEM,ITEM,DESCRIPCION,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,...,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO,TIENE,PRECIO
1,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN

TAREA:

1.   Renombrar las columnas
2.   Validar el tipo de las variables y hacer que las variables de precio sean tipo float
3. IDEA (¬øC√≥mo podemos transformar la tabla para el an√°lisis?)

In [ ]:
# Renombrando las columnas
countter = 0
new_names = []
for col in data.columns:
  if pd.isna(col):
    new_names.append(f'No Name{countter}')
  else:
    new_names.append(col)
  countter = countter + 1

data.columns = new_names

In [ ]:
row_1 = data.iloc[0]
row_1

No Name0                                  N¬∞ ITEM
No Name1                                     ITEM
No Name2                              DESCRIPCION
MEDICAL B & T                               TIENE
No Name4                                   PRECIO
MONT GROUP                                  TIENE
No Name6                                   PRECIO
ALFY MEDICA S.A.C                           TIENE
No Name8                                   PRECIO
BEE MEDICAL                                 TIENE
No Name10                                  PRECIO
ALKOFARMA                                   TIENE
No Name12                                  PRECIO
VALCAM                                      TIENE
No Name14                                  PRECIO
FAMILY DOCTOR                               TIENE
No Name16                                  PRECIO
GE PHARMA                                   TIENE
No Name18                                  PRECIO
IRSA                                        TIENE
No Name20                                  PRECIO
KANGJI                                      TIENE
No Name22                                  PRECIO
LAPE                                        TIENE
No Name24                                  PRECIO
GEOMEDIC                                    TIENE
No Name26                                  PRECIO
IQ MEDIC                                    TIENE
No Name28                                  PRECIO
DROGUERIA IMP. DE ART MEDICOS S.A.          TIENE
No Name30                                  PRECIO
SOMOS                                       TIENE
No Name32                                  PRECIO
Name: 0, dtype: object

In [ ]:
column_names = list(data.columns)

type(column_names)

list

In [ ]:
data.columns

Index(['No Name0', 'No Name1', 'No Name2', 'MEDICAL B & T', 'No Name4',
       'MONT GROUP', 'No Name6', 'ALFY MEDICA S.A.C', 'No Name8',
       'BEE MEDICAL', 'No Name10', 'ALKOFARMA', 'No Name12', 'VALCAM',
       'No Name14', 'FAMILY DOCTOR', 'No Name16', 'GE PHARMA', 'No Name18',
       'IRSA', 'No Name20', 'KANGJI', 'No Name22', 'LAPE', 'No Name24',
       'GEOMEDIC', 'No Name26', 'IQ MEDIC', 'No Name28',
       'DROGUERIA IMP. DE ART MEDICOS S.A.', 'No Name30', 'SOMOS',
       'No Name32'],
      dtype='object')

In [ ]:
#Vamos a encontrar la posicion de las columnas que queremos renombrar

column_pos = [0,1,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32]

In [ ]:
dic_rownames = {}

In [ ]:
for x in column_pos:
  name = data.columns[x]
  new_name = row_1.iloc[x]
  dic_rownames[name] = new_name

In [ ]:
dic_rownames

{'No Name0': 'N¬∞ ITEM',
 'No Name1': 'ITEM',
 'No Name2': 'DESCRIPCION',
 'No Name4': 'PRECIO',
 'No Name6': 'PRECIO',
 'No Name8': 'PRECIO',
 'No Name10': 'PRECIO',
 'No Name12': 'PRECIO',
 'No Name14': 'PRECIO',
 'No Name16': 'PRECIO',
 'No Name18': 'PRECIO',
 'No Name20': 'PRECIO',
 'No Name22': 'PRECIO',
 'No Name24': 'PRECIO',
 'No Name26': 'PRECIO',
 'No Name28': 'PRECIO',
 'No Name30': 'PRECIO',
 'No Name32': 'PRECIO'}

In [ ]:
#Renombrando la primera fila

data = data.rename(columns=dic_rownames).drop(index=0)
data = data.reset_index(drop = True)

In [ ]:
data.head()

,N¬∞ ITEM,ITEM,DESCRIPCION,MEDICAL B & T,PRECIO,MONT GROUP,PRECIO,ALFY MEDICA S.A.C,PRECIO,BEE MEDICAL,...,LAPE,PRECIO,GEOMEDIC,PRECIO,IQ MEDIC,PRECIO,DROGUERIA IMP. DE ART MEDICOS S.A.,PRECIO,SOMOS,PRECIO
0,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
1,002,NaN,"3"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
2,003,NaN,"4"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
3,004,NaN,"5"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
4,005,NaN,"6"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN

In [ ]:
number = list(range(1,data.shape[0]+1))

In [ ]:
data['N¬∞ ITEM'] = number

In [ ]:
data.head()

,N¬∞ ITEM,ITEM,DESCRIPCION,MEDICAL B & T,PRECIO,MONT GROUP,PRECIO,ALFY MEDICA S.A.C,PRECIO,BEE MEDICAL,...,LAPE,PRECIO,GEOMEDIC,PRECIO,IQ MEDIC,PRECIO,DROGUERIA IMP. DE ART MEDICOS S.A.,PRECIO,SOMOS,PRECIO
0,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
1,2,NaN,"3"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
2,3,NaN,"4"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
3,4,NaN,"5"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN
4,5,NaN,"6"" X 5 YARDAS",True,NaN,False,NaN,False,NaN,False,...,True,NaN,False,NaN,False,NaN,True,NaN,False,NaN

In [ ]:
#Cambiando el valor de precio de Nan a 0

data['PRECIO'] = 0

In [ ]:
data.head()

,N¬∞ ITEM,ITEM,DESCRIPCION,MEDICAL B & T,PRECIO,MONT GROUP,PRECIO,ALFY MEDICA S.A.C,PRECIO,BEE MEDICAL,...,LAPE,PRECIO,GEOMEDIC,PRECIO,IQ MEDIC,PRECIO,DROGUERIA IMP. DE ART MEDICOS S.A.,PRECIO,SOMOS,PRECIO
0,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
1,2,NaN,"3"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
2,3,NaN,"4"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
3,4,NaN,"5"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
4,5,NaN,"6"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0

In [ ]:
#Copiando todos los valores de items

for y in range(0,data.shape[0]):
  if pd.notna(data.loc[y,'ITEM']):
    aux = data.loc[y,'ITEM']
  else:
    data.loc[y,'ITEM'] = aux

In [ ]:
data.head(20)

,N¬∞ ITEM,ITEM,DESCRIPCION,MEDICAL B & T,PRECIO,MONT GROUP,PRECIO,ALFY MEDICA S.A.C,PRECIO,BEE MEDICAL,...,LAPE,PRECIO,GEOMEDIC,PRECIO,IQ MEDIC,PRECIO,DROGUERIA IMP. DE ART MEDICOS S.A.,PRECIO,SOMOS,PRECIO
0,1,VENDAS ELASTICAS,"2"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
1,2,VENDAS ELASTICAS,"3"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
2,3,VENDAS ELASTICAS,"4"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
3,4,VENDAS ELASTICAS,"5"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
4,5,VENDAS ELASTICAS,"6"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
5,6,VENDAS ELASTICAS,"8"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
6,7,VENDAS ELASTICAS,"10"" X 5 YARDAS",True,0,False,0,False,0,False,...,True,0,False,0,False,0,True,0,False,0
7,8,VENDAS ELASTICAS,"12"" X 5 YARDAS",False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
8,9,VENAS DE YESO,"4"" X 5 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,True,0,True,0,False,0
9,10,VENAS DE YESO,"6"" X 5 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,True,0,False,0,False,0
10,11,VENAS DE YESO,"8"" X 5 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,True,0,False,0,False,0
11,12,ALGODON EN VENDAS,"3"" X 3 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
12,13,ALGODON EN VENDAS,"4"" X 3 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
13,14,ALGODON EN VENDAS,"6"" X 3 YARDS",False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
14,15,VENDA DE YESO ACRILICO,ROSADO,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
15,16,VENDA DE YESO ACRILICO,ROJO,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
16,17,VENDA DE YESO ACRILICO,NARANJA,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
17,18,VENDA DE YESO ACRILICO,AMARILLO,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
18,19,VENDA DE YESO ACRILICO,VERDE CLARO,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0
19,20,VENDA DE YESO ACRILICO,VERDE,False,0,False,0,False,0,False,...,True,0,False,0,False,0,False,0,False,0

In [ ]:
data.dtypes

N¬∞ ITEM                                int64
ITEM                                  object
DESCRIPCION                           object
MEDICAL B & T                         object
PRECIO                                 int64
MONT GROUP                            object
PRECIO                                 int64
ALFY MEDICA S.A.C                     object
PRECIO                                 int64
BEE MEDICAL                           object
PRECIO                                 int64
ALKOFARMA                             object
PRECIO                                 int64
VALCAM                                object
PRECIO                                 int64
FAMILY DOCTOR                         object
PRECIO                                 int64
GE PHARMA                             object
PRECIO                                 int64
IRSA                                  object
PRECIO                                 int64
KANGJI                                object
PRECIO                                 int64
LAPE                                  object
PRECIO                                 int64
GEOMEDIC                              object
PRECIO                                 int64
IQ MEDIC                              object
PRECIO                                 int64
DROGUERIA IMP. DE ART MEDICOS S.A.    object
PRECIO                                 int64
SOMOS                                 object
PRECIO                                 int64
dtype: object

In [ ]:
data.isnull().sum()

N¬∞ ITEM                               0
ITEM                                  0
DESCRIPCION                           6
MEDICAL B & T                         1
PRECIO                                0
MONT GROUP                            1
PRECIO                                0
ALFY MEDICA S.A.C                     1
PRECIO                                0
BEE MEDICAL                           1
PRECIO                                0
ALKOFARMA                             0
PRECIO                                0
VALCAM                                1
PRECIO                                0
FAMILY DOCTOR                         1
PRECIO                                0
GE PHARMA                             1
PRECIO                                0
IRSA                                  1
PRECIO                                0
KANGJI                                1
PRECIO                                0
LAPE                                  1
PRECIO                                0
GEOMEDIC                              1
PRECIO                                0
IQ MEDIC                              1
PRECIO                                0
DROGUERIA IMP. DE ART MEDICOS S.A.    1
PRECIO                                0
SOMOS                                 1
PRECIO                                0
dtype: int64

TAREA



1.   Renombrar las columnas precios que sea Precio-Empresa
2.   Volver las variables precio de int a float
3.   Hacer el tratamiento a los nulos y que la tabla tenga 0 valores nulos en   cada columna